Changed from py2neo to neo4j-driver for loading data to server
Code ended up more verbose, though seemingly slightly faster

Still not compatible with Jython, receiving the following error:

/home/andrew/jython2.7.0/Lib/site-packages/neo4j/v1/security.py:127: UserWarning: Bolt over TLS is only available in Python 2.7.9+ and Python 3.3+ so communications are not secure
  warn("Bolt over TLS is only available in Python 2.7.9+ and Python 3.3+ "
  Could not load graph. Check password.
  Exception: [Errno 92] Protocol not available

Suspend hopes of running server loading in Jython for now. Focus on providing interface for giving data to embedded instance